### ISSUE TITLE
关于metapath生成

### ISSUE THREAD

**Issue by RyanWangZf** [googlebaba/KDD2019-MEIRec#1]
你好 能请教一下你这里数据预处理的时候metapath是怎么生成的吗？是random walk还是什么？
能不能release一下代码参考一下？
谢谢

**Comment by googlebaba** [comment]
元路径是预先设定的，比如U-I-Q,Q-I-U,然后基于元路径找U或Q的一阶和二阶邻居，元路径查找邻居这部分代码没办法release，主要就是用SQL里的JOIN操作实现的。

**Comment by RyanWangZf** [comment]
> 元路径是预先设定的，比如U-I-Q,Q-I-U,然后基于元路径找U或Q的一阶和二阶邻居，元路径查找邻居这部分代码没办法release，主要就是用SQL里的JOIN操作实现的。

寻找邻居的时候是所有邻居还是采样一个固定数量的邻居呢？

**Comment by googlebaba** [comment]
采固定数量的邻居 ，通常是top5-10，比如U-I取user最近点击的10个item, Q-I去 query引导的最多的10个item。
