### ISSUE TITLE
节点嵌入

### ISSUE THREAD

**Issue by YEA02** [googlebaba/KDD2019-MEIRec#2]
你好，请问最后可以得到节点嵌入吗 ？对应的输出是什么？

**Comment by googlebaba** [comment]
应该可以得到user和query的嵌入，对应于论文中的Eq.5和Eq.6，但是我们是针对于链路预测优化的，对于分类或者聚类任务不一定会有好的效果

**Comment by YEA02** [comment]
谢谢！可以提示一下对应于代码是哪里得到了user和query的嵌入吗？
还想请问一下，基于元路径获取的邻居节点是已经在数据部分就处理好了吗

**Comment by googlebaba** [comment]
1.MultiRecallSimpV1_exp_U_iq_qi_Q_ui_iq_lstm_cnn.py 的第264，将不同元路径拼接起来就可以了
2.是的，这样模型代码比较简洁。

**Comment by YEA02** [comment]
好的，感谢！
